// <auto-generated />
using System;
using LibraryManager.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LibraryManager.Models.ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<bool>("DaTra")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuongMuon")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuMuon", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("LibraryManager.Models.ChiTietPhieuTra", b =>
                {
                    b.Property<int>("MaPhieuTra")
                        .HasColumnType("int");

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuTra", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTietPhieuTras");
                });

            modelBuilder.Entity("LibraryManager.Models.DocGia", b =>
                {
                    b.Property<int>("MaDocGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDocGia"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDocGia");

                    b.ToTable("DocGias");

                    b.HasData(
                        new
                        {
                            MaDocGia = 1,
                            DiaChi = "Hà Nội",
                            Email = "vana1@gmail.com",
                            NgaySinh = new DateTime(1998, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0912345678",
                            Ten = "Nguyễn Văn A"
                        },
                        new
                        {
                            MaDocGia = 2,
                            DiaChi = "TP.HCM",
                            Email = "thib2@yahoo.com",
                            NgaySinh = new DateTime(1997, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0987654321",
                            Ten = "Trần Thị B"
                        },
                        new
                        {
                            MaDocGia = 3,
                            DiaChi = "Đà Nẵng",
                            Email = "le.c3@hotmail.com",
                            NgaySinh = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0901234567",
                            Ten = "Lê Văn C"
                        },
                        new
                        {
                            MaDocGia = 4,
                            DiaChi = "Cần Thơ",
                            Email = "phamd4@gmail.com",
                            NgaySinh = new DateTime(2000, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0932123456",
                            Ten = "Phạm Thị D"
                        },
                        new
                        {
                            MaDocGia = 5,
                            DiaChi = "Hải Phòng",
                            Email = "ehoang5@gmail.com",
                            NgaySinh = new DateTime(1999, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0967890123",
                            Ten = "Hoàng Văn E"
                        },
                        new
                        {
                            MaDocGia = 6,
                            DiaChi = "Quảng Ninh",
                            Email = "f.d6@gmail.com",
                            NgaySinh = new DateTime(2001, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0978901234",
                            Ten = "Đỗ Thị F"
                        },
                        new
                        {
                            MaDocGia = 7,
                            DiaChi = "Huế",
                            Email = "gvu7@gmail.com",
                            NgaySinh = new DateTime(1996, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0911223344",
                            Ten = "Vũ Văn G"
                        },
                        new
                        {
                            MaDocGia = 8,
                            DiaChi = "Nghệ An",
                            Email = "hngo8@yahoo.com",
                            NgaySinh = new DateTime(1994, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0922334455",
                            Ten = "Ngô Thị H"
                        },
                        new
                        {
                            MaDocGia = 9,
                            DiaChi = "Bình Dương",
                            Email = "ibui9@gmail.com",
                            NgaySinh = new DateTime(1993, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0933445566",
                            Ten = "Bùi Văn I"
                        },
                        new
                        {
                            MaDocGia = 10,
                            DiaChi = "Đắk Lắk",
                            Email = "kdang10@gmail.com",
                            NgaySinh = new DateTime(1992, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0944556677",
                            Ten = "Đặng Thị K"
                        },
                        new
                        {
                            MaDocGia = 11,
                            DiaChi = "Hòa Bình",
                            Email = "ltrinh11@gmail.com",
                            NgaySinh = new DateTime(1991, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0955667788",
                            Ten = "Trịnh Văn L"
                        },
                        new
                        {
                            MaDocGia = 12,
                            DiaChi = "Ninh Bình",
                            Email = "mphan12@gmail.com",
                            NgaySinh = new DateTime(1990, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0966778899",
                            Ten = "Phan Thị M"
                        },
                        new
                        {
                            MaDocGia = 13,
                            DiaChi = "Thanh Hóa",
                            Email = "nly13@gmail.com",
                            NgaySinh = new DateTime(1989, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0977889900",
                            Ten = "Lý Văn N"
                        },
                        new
                        {
                            MaDocGia = 14,
                            DiaChi = "Phú Thọ",
                            Email = "ota14@gmail.com",
                            NgaySinh = new DateTime(1998, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0988990011",
                            Ten = "Tạ Thị O"
                        },
                        new
                        {
                            MaDocGia = 15,
                            DiaChi = "Nam Định",
                            Email = "p.dinh15@gmail.com",
                            NgaySinh = new DateTime(1997, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0999001122",
                            Ten = "Đinh Văn P"
                        },
                        new
                        {
                            MaDocGia = 16,
                            DiaChi = "Thái Bình",
                            Email = "q.ha16@gmail.com",
                            NgaySinh = new DateTime(1996, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0900112233",
                            Ten = "Hà Thị Q"
                        },
                        new
                        {
                            MaDocGia = 17,
                            DiaChi = "Lào Cai",
                            Email = "rtruong17@gmail.com",
                            NgaySinh = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0911223345",
                            Ten = "Trương Văn R"
                        },
                        new
                        {
                            MaDocGia = 18,
                            DiaChi = "Bắc Giang",
                            Email = "scao18@gmail.com",
                            NgaySinh = new DateTime(1994, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0922334456",
                            Ten = "Cao Thị S"
                        },
                        new
                        {
                            MaDocGia = 19,
                            DiaChi = "Tuyên Quang",
                            Email = "tkieu19@gmail.com",
                            NgaySinh = new DateTime(1993, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0933445567",
                            Ten = "Kiều Văn T"
                        },
                        new
                        {
                            MaDocGia = 20,
                            DiaChi = "Yên Bái",
                            Email = "ulam20@gmail.com",
                            NgaySinh = new DateTime(1992, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0944556678",
                            Ten = "Lâm Thị U"
                        },
                        new
                        {
                            MaDocGia = 21,
                            DiaChi = "Hà Giang",
                            Email = "vchau21@gmail.com",
                            NgaySinh = new DateTime(1991, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0955667789",
                            Ten = "Châu Văn V"
                        },
                        new
                        {
                            MaDocGia = 22,
                            DiaChi = "Sơn La",
                            Email = "xtrinh22@gmail.com",
                            NgaySinh = new DateTime(1990, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0966778890",
                            Ten = "Trịnh Thị X"
                        },
                        new
                        {
                            MaDocGia = 23,
                            DiaChi = "Lạng Sơn",
                            Email = "ytong23@gmail.com",
                            NgaySinh = new DateTime(1989, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0977889901",
                            Ten = "Tống Văn Y"
                        },
                        new
                        {
                            MaDocGia = 24,
                            DiaChi = "Bắc Ninh",
                            Email = "zmai24@gmail.com",
                            NgaySinh = new DateTime(1988, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0988990012",
                            Ten = "Mai Thị Z"
                        },
                        new
                        {
                            MaDocGia = 25,
                            DiaChi = "Quảng Nam",
                            Email = "aa.ng25@gmail.com",
                            NgaySinh = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0999001123",
                            Ten = "Nguyễn Văn AA"
                        },
                        new
                        {
                            MaDocGia = 26,
                            DiaChi = "Bình Phước",
                            Email = "bbtran26@gmail.com",
                            NgaySinh = new DateTime(1998, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0900112234",
                            Ten = "Trần Thị BB"
                        },
                        new
                        {
                            MaDocGia = 27,
                            DiaChi = "Tây Ninh",
                            Email = "ccle27@gmail.com",
                            NgaySinh = new DateTime(1997, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0911223346",
                            Ten = "Lê Văn CC"
                        },
                        new
                        {
                            MaDocGia = 28,
                            DiaChi = "Hậu Giang",
                            Email = "ddpham28@gmail.com",
                            NgaySinh = new DateTime(1996, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0922334457",
                            Ten = "Phạm Thị DD"
                        },
                        new
                        {
                            MaDocGia = 29,
                            DiaChi = "Vĩnh Long",
                            Email = "eehoang29@gmail.com",
                            NgaySinh = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0933445568",
                            Ten = "Hoàng Văn EE"
                        },
                        new
                        {
                            MaDocGia = 30,
                            DiaChi = "Trà Vinh",
                            Email = "ffdo30@gmail.com",
                            NgaySinh = new DateTime(1994, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0944556679",
                            Ten = "Đỗ Thị FF"
                        });
                });

            modelBuilder.Entity("LibraryManager.Models.PhieuMuon", b =>
                {
                    b.Property<int>("MaPhieuMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuMuon"), 1L, 1);

                    b.Property<DateTime>("HanTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaDocGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuMuon");

                    b.HasIndex("MaDocGia");

                    b.ToTable("PhieuMuons");
                });

            modelBuilder.Entity("LibraryManager.Models.PhieuPhat", b =>
                {
                    b.Property<int>("MaPhieuPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuPhat"), 1L, 1);

                    b.Property<bool>("DaThuTien")
                        .HasColumnType("bit");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDocGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuPhat");

                    b.HasIndex("MaDocGia");

                    b.ToTable("PhieuPhats");

                    b.HasData(
                        new
                        {
                            MaPhieuPhat = 1,
                            DaThuTien = true,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 1,
                            NgayLap = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 15000m
                        },
                        new
                        {
                            MaPhieuPhat = 2,
                            DaThuTien = false,
                            LyDo = "Làm hỏng sách",
                            MaDocGia = 2,
                            NgayLap = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 20000m
                        },
                        new
                        {
                            MaPhieuPhat = 3,
                            DaThuTien = true,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 3,
                            NgayLap = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 5000m
                        },
                        new
                        {
                            MaPhieuPhat = 4,
                            DaThuTien = false,
                            LyDo = "Mất sách",
                            MaDocGia = 4,
                            NgayLap = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 10000m
                        },
                        new
                        {
                            MaPhieuPhat = 5,
                            DaThuTien = true,
                            LyDo = "Làm hỏng sách",
                            MaDocGia = 5,
                            NgayLap = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 25000m
                        },
                        new
                        {
                            MaPhieuPhat = 6,
                            DaThuTien = false,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 6,
                            NgayLap = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 5000m
                        },
                        new
                        {
                            MaPhieuPhat = 7,
                            DaThuTien = true,
                            LyDo = "Không trả sách đầy đủ",
                            MaDocGia = 7,
                            NgayLap = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 30000m
                        },
                        new
                        {
                            MaPhieuPhat = 8,
                            DaThuTien = true,
                            LyDo = "Ghi chú sai thông tin",
                            MaDocGia = 8,
                            NgayLap = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 10000m
                        },
                        new
                        {
                            MaPhieuPhat = 9,
                            DaThuTien = false,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 9,
                            NgayLap = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 15000m
                        },
                        new
                        {
                            MaPhieuPhat = 10,
                            DaThuTien = true,
                            LyDo = "Làm hỏng sách",
                            MaDocGia = 10,
                            NgayLap = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 20000m
                        },
                        new
                        {
                            MaPhieuPhat = 11,
                            DaThuTien = false,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 11,
                            NgayLap = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 10000m
                        },
                        new
                        {
                            MaPhieuPhat = 12,
                            DaThuTien = true,
                            LyDo = "Mất sách",
                            MaDocGia = 12,
                            NgayLap = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 20000m
                        },
                        new
                        {
                            MaPhieuPhat = 13,
                            DaThuTien = false,
                            LyDo = "Làm hỏng sách",
                            MaDocGia = 13,
                            NgayLap = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 25000m
                        },
                        new
                        {
                            MaPhieuPhat = 14,
                            DaThuTien = true,
                            LyDo = "Không trả sách đầy đủ",
                            MaDocGia = 14,
                            NgayLap = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 30000m
                        },
                        new
                        {
                            MaPhieuPhat = 15,
                            DaThuTien = false,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 15,
                            NgayLap = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 5000m
                        },
                        new
                        {
                            MaPhieuPhat = 16,
                            DaThuTien = true,
                            LyDo = "Làm hỏng sách",
                            MaDocGia = 16,
                            NgayLap = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 15000m
                        },
                        new
                        {
                            MaPhieuPhat = 17,
                            DaThuTien = false,
                            LyDo = "Mất sách",
                            MaDocGia = 17,
                            NgayLap = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 20000m
                        },
                        new
                        {
                            MaPhieuPhat = 18,
                            DaThuTien = true,
                            LyDo = "Ghi chú sai thông tin",
                            MaDocGia = 18,
                            NgayLap = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 10000m
                        },
                        new
                        {
                            MaPhieuPhat = 19,
                            DaThuTien = true,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 19,
                            NgayLap = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 15000m
                        },
                        new
                        {
                            MaPhieuPhat = 20,
                            DaThuTien = false,
                            LyDo = "Không trả sách đầy đủ",
                            MaDocGia = 20,
                            NgayLap = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 30000m
                        },
                        new
                        {
                            MaPhieuPhat = 21,
                            DaThuTien = true,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 21,
                            NgayLap = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 5000m
                        },
                        new
                        {
                            MaPhieuPhat = 22,
                            DaThuTien = false,
                            LyDo = "Mất sách",
                            MaDocGia = 22,
                            NgayLap = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 20000m
                        },
                        new
                        {
                            MaPhieuPhat = 23,
                            DaThuTien = true,
                            LyDo = "Làm hỏng sách",
                            MaDocGia = 23,
                            NgayLap = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 25000m
                        },
                        new
                        {
                            MaPhieuPhat = 24,
                            DaThuTien = false,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 24,
                            NgayLap = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 15000m
                        },
                        new
                        {
                            MaPhieuPhat = 25,
                            DaThuTien = true,
                            LyDo = "Ghi chú sai thông tin",
                            MaDocGia = 25,
                            NgayLap = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 10000m
                        },
                        new
                        {
                            MaPhieuPhat = 26,
                            DaThuTien = true,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 26,
                            NgayLap = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 5000m
                        },
                        new
                        {
                            MaPhieuPhat = 27,
                            DaThuTien = false,
                            LyDo = "Không trả sách đầy đủ",
                            MaDocGia = 27,
                            NgayLap = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 30000m
                        },
                        new
                        {
                            MaPhieuPhat = 28,
                            DaThuTien = true,
                            LyDo = "Trả sách trễ",
                            MaDocGia = 28,
                            NgayLap = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 15000m
                        },
                        new
                        {
                            MaPhieuPhat = 29,
                            DaThuTien = false,
                            LyDo = "Làm hỏng sách",
                            MaDocGia = 29,
                            NgayLap = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 20000m
                        },
                        new
                        {
                            MaPhieuPhat = 30,
                            DaThuTien = true,
                            LyDo = "Mất sách",
                            MaDocGia = 30,
                            NgayLap = new DateTime(2025, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoTienPhat = 10000m
                        });
                });

            modelBuilder.Entity("LibraryManager.Models.PhieuTra", b =>
                {
                    b.Property<int>("MaPhieuTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuTra"), 1L, 1);

                    b.Property<int>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuTra");

                    b.HasIndex("MaPhieuMuon");

                    b.ToTable("PhieuTras");
                });

            modelBuilder.Entity("LibraryManager.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"), 1L, 1);

                    b.Property<string>("NXB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSach");

                    b.ToTable("Saches");

                    b.HasData(
                        new
                        {
                            MaSach = 1,
                            NXB = "NXB Kim Đồng",
                            NamXuatBan = 2012,
                            SoLuong = 28,
                            TacGia = "Nguyễn Nhật Ánh",
                            Ten = "Harry Potter và Hòn Đá Phù Thủy",
                            TheLoai = "Giáo dục"
                        },
                        new
                        {
                            MaSach = 2,
                            NXB = "NXB Trẻ",
                            NamXuatBan = 2020,
                            SoLuong = 45,
                            TacGia = "Nam Cao",
                            Ten = "Đắc Nhân Tâm",
                            TheLoai = "Tâm lý"
                        },
                        new
                        {
                            MaSach = 3,
                            NXB = "NXB Kim Đồng",
                            NamXuatBan = 2015,
                            SoLuong = 32,
                            TacGia = "To Hoai",
                            Ten = "Dế Mèn Phiêu Lưu Ký",
                            TheLoai = "Thiếu nhi"
                        },
                        new
                        {
                            MaSach = 4,
                            NXB = "NXB Trẻ",
                            NamXuatBan = 2016,
                            SoLuong = 40,
                            TacGia = "Nguyễn Nhật Ánh",
                            Ten = "Tôi Thấy Hoa Vàng Trên Cỏ Xanh",
                            TheLoai = "Văn học"
                        },
                        new
                        {
                            MaSach = 5,
                            NXB = "NXB Giáo Dục",
                            NamXuatBan = 2010,
                            SoLuong = 18,
                            TacGia = "Ngô Tất Tố",
                            Ten = "Lão Hạc",
                            TheLoai = "Truyện ngắn"
                        },
                        new
                        {
                            MaSach = 6,
                            NXB = "NXB Văn Học",
                            NamXuatBan = 2013,
                            SoLuong = 25,
                            TacGia = "Nguyễn Du",
                            Ten = "Chiếc Thuyền Ngoài Xa",
                            TheLoai = "Văn học"
                        },
                        new
                        {
                            MaSach = 7,
                            NXB = "NXB Trẻ",
                            NamXuatBan = 2014,
                            SoLuong = 38,
                            TacGia = "Truyện Dân Gian",
                            Ten = "Tuổi Thơ Dữ Dội",
                            TheLoai = "Lịch sử"
                        },
                        new
                        {
                            MaSach = 8,
                            NXB = "NXB Văn Học",
                            NamXuatBan = 2021,
                            SoLuong = 15,
                            TacGia = "Nam Cao",
                            Ten = "Số Đỏ",
                            TheLoai = "Truyện ngắn"
                        },
                        new
                        {
                            MaSach = 9,
                            NXB = "NXB Văn Học",
                            NamXuatBan = 2012,
                            SoLuong = 30,
                            TacGia = "Ngô Tất Tố",
                            Ten = "Chí Phèo",
                            TheLoai = "Truyện ngắn"
                        },
                        new
                        {
                            MaSach = 10,
                            NXB = "NXB Trẻ",
                            NamXuatBan = 2019,
                            SoLuong = 20,
                            TacGia = "Nguyễn Nhật Ánh",
                            Ten = "Nhà Giả Kim",
                            TheLoai = "Văn học"
                        },
                        new
                        {
                            MaSach = 11,
                            NXB = "NXB Giáo Dục",
                            NamXuatBan = 2004,
                            SoLuong = 16,
                            TacGia = "J.K. Rowling",
                            Ten = "1984",
                            TheLoai = "Khoa học"
                        },
                        new
                        {
                            MaSach = 12,
                            NXB = "NXB Tổng hợp",
                            NamXuatBan = 2020,
                            SoLuong = 22,
                            TacGia = "Nguyễn Du",
                            Ten = "Bắt Trẻ Đồng Xanh",
                            TheLoai = "Tâm lý"
                        },
                        new
                        {
                            MaSach = 13,
                            NXB = "NXB Kim Đồng",
                            NamXuatBan = 2011,
                            SoLuong = 17,
                            TacGia = "To Hoai",
                            Ten = "Ông Già Và Biển Cả",
                            TheLoai = "Lịch sử"
                        },
                        new
                        {
                            MaSach = 14,
                            NXB = "NXB Trẻ",
                            NamXuatBan = 2005,
                            SoLuong = 29,
                            TacGia = "Nguyễn Nhật Ánh",
                            Ten = "Không Gia Đình",
                            TheLoai = "Truyện ngắn"
                        },
                        new
                        {
                            MaSach = 15,
                            NXB = "NXB Tổng hợp",
                            NamXuatBan = 2022,
                            SoLuong = 34,
                            TacGia = "Nam Cao",
                            Ten = "Cuộc Đời Của Pi",
                            TheLoai = "Văn học"
                        },
                        new
                        {
                            MaSach = 16,
                            NXB = "NXB Kim Đồng",
                            NamXuatBan = 2018,
                            SoLuong = 26,
                            TacGia = "To Hoai",
                            Ten = "Kính Vạn Hoa",
                            TheLoai = "Thiếu nhi"
                        },
                        new
                        {
                            MaSach = 17,
                            NXB = "NXB Giáo Dục",
                            NamXuatBan = 2016,
                            SoLuong = 31,
                            TacGia = "Nguyễn Du",
                            Ten = "Người Bán Hàng Vĩ Đại Nhất Thế Giới",
                            TheLoai = "Giáo dục"
                        },
                        new
                        {
                            MaSach = 18,
                            NXB = "NXB Tổng hợp",
                            NamXuatBan = 2007,
                            SoLuong = 19,
                            TacGia = "Truyện Dân Gian",
                            Ten = "Vượt Lên Người Khổng Lồ",
                            TheLoai = "Tâm lý"
                        },
                        new
                        {
                            MaSach = 19,
                            NXB = "NXB Văn Học",
                            NamXuatBan = 2014,
                            SoLuong = 35,
                            TacGia = "Nguyễn Nhật Ánh",
                            Ten = "Bí Mật Của Phan Thiên Ân",
                            TheLoai = "Tâm lý"
                        },
                        new
                        {
                            MaSach = 20,
                            NXB = "NXB Giáo Dục",
                            NamXuatBan = 2003,
                            SoLuong = 40,
                            TacGia = "To Hoai",
                            Ten = "Totto-chan Bên Cửa Sổ",
                            TheLoai = "Thiếu nhi"
                        },
                        new
                        {
                            MaSach = 21,
                            NXB = "NXB Trẻ",
                            NamXuatBan = 2017,
                            SoLuong = 22,
                            TacGia = "Nam Cao",
                            Ten = "Muôn Kiếp Nhân Sinh",
                            TheLoai = "Văn học"
                        },
                        new
                        {
                            MaSach = 22,
                            NXB = "NXB Giáo Dục",
                            NamXuatBan = 2015,
                            SoLuong = 44,
                            TacGia = "Nguyễn Du",
                            Ten = "Truyện Kiều",
                            TheLoai = "Văn học"
                        },
                        new
                        {
                            MaSach = 23,
                            NXB = "NXB Kim Đồng",
                            NamXuatBan = 2008,
                            SoLuong = 39,
                            TacGia = "Nguyễn Nhật Ánh",
                            Ten = "Mắt Biếc",
                            TheLoai = "Truyện ngắn"
                        },
                        new
                        {
                            MaSach = 24,
                            NXB = "NXB Văn Học",
                            NamXuatBan = 2006,
                            SoLuong = 18,
                            TacGia = "Nguyễn Du",
                            Ten = "Đồi Gió Hú",
                            TheLoai = "Tâm lý"
                        },
                        new
                        {
                            MaSach = 25,
                            NXB = "NXB Giáo Dục",
                            NamXuatBan = 2009,
                            SoLuong = 23,
                            TacGia = "Ngô Tất Tố",
                            Ten = "Những Tấm Lòng Cao Cả",
                            TheLoai = "Giáo dục"
                        },
                        new
                        {
                            MaSach = 26,
                            NXB = "NXB Văn Học",
                            NamXuatBan = 2011,
                            SoLuong = 24,
                            TacGia = "Truyện Dân Gian",
                            Ten = "Con Đường Hồi Giáo",
                            TheLoai = "Lịch sử"
                        },
                        new
                        {
                            MaSach = 27,
                            NXB = "NXB Tổng hợp",
                            NamXuatBan = 2002,
                            SoLuong = 12,
                            TacGia = "Nguyễn Nhật Ánh",
                            Ten = "Tự Truyện Lý Tiểu Long",
                            TheLoai = "Lịch sử"
                        },
                        new
                        {
                            MaSach = 28,
                            NXB = "NXB Trẻ",
                            NamXuatBan = 2013,
                            SoLuong = 27,
                            TacGia = "Nguyễn Du",
                            Ten = "Bố Già",
                            TheLoai = "Tâm lý"
                        },
                        new
                        {
                            MaSach = 29,
                            NXB = "NXB Giáo Dục",
                            NamXuatBan = 2023,
                            SoLuong = 33,
                            TacGia = "Nam Cao",
                            Ten = "Thiên Tài Bên Trái, Kẻ Điên Bên Phải",
                            TheLoai = "Khoa học"
                        },
                        new
                        {
                            MaSach = 30,
                            NXB = "NXB Tổng hợp",
                            NamXuatBan = 2001,
                            SoLuong = 21,
                            TacGia = "To Hoai",
                            Ten = "Cuốn Theo Chiều Gió",
                            TheLoai = "Văn học"
                        });
                });

            modelBuilder.Entity("LibraryManager.Models.TaiKhoan", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserName");

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            UserName = "admin1",
                            PassWord = "123456",
                            Role = "Admin"
                        },
                        new
                        {
                            UserName = "admin2",
                            PassWord = "admin@2025",
                            Role = "Admin"
                        },
                        new
                        {
                            UserName = "manager1",
                            PassWord = "manager123",
                            Role = "Manager"
                        },
                        new
                        {
                            UserName = "manager2",
                            PassWord = "qwerty",
                            Role = "Manager"
                        },
                        new
                        {
                            UserName = "admin3",
                            PassWord = "admin789",
                            Role = "Admin"
                        },
                        new
                        {
                            UserName = "manager3",
                            PassWord = "m@2025",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("LibraryManager.Models.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("LibraryManager.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManager.Models.Sach", "Sach")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryManager.Models.ChiTietPhieuTra", b =>
                {
                    b.HasOne("LibraryManager.Models.PhieuTra", "PhieuTra")
                        .WithMany("ChiTietPhieuTras")
                        .HasForeignKey("MaPhieuTra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManager.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuTra");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryManager.Models.PhieuMuon", b =>
                {
                    b.HasOne("LibraryManager.Models.DocGia", "DocGia")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("MaDocGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("LibraryManager.Models.PhieuPhat", b =>
                {
                    b.HasOne("LibraryManager.Models.DocGia", "DocGia")
                        .WithMany("PhieuThuTienPhats")
                        .HasForeignKey("MaDocGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("LibraryManager.Models.PhieuTra", b =>
                {
                    b.HasOne("LibraryManager.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("PhieuTras")
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("LibraryManager.Models.DocGia", b =>
                {
                    b.Navigation("PhieuMuons");

                    b.Navigation("PhieuThuTienPhats");
                });

            modelBuilder.Entity("LibraryManager.Models.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");

                    b.Navigation("PhieuTras");
                });

            modelBuilder.Entity("LibraryManager.Models.PhieuTra", b =>
                {
                    b.Navigation("ChiTietPhieuTras");
                });

            modelBuilder.Entity("LibraryManager.Models.Sach", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });
#pragma warning restore 612, 618
        }
    }
}
